<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p id="Promises"></p>
    <p id="PromiseState"></p>
    <p> We all make mistakes and also our script can handle errors, Usually a program halts or close abruptly when it encounters an error, so we use
        try catch to avoid the sudden closure of the program
    </p>
    <p>
        there are errors which are purposefully generated to check the logic or whatever the reason it is,
        but further execution of the code must not be stopped and therefore we use try catch
    </p>

    <p>
        try{
            scheduled code
        }
        catch (error){
            console.log("There is some error in the scheduled code")
        }
    </p>

    <p> Custom errors and Error Objects </p>
    <ul> For all the built in errors, the error has some custom properties they are as follows
        <li>name</li>
        <li>message</li>
    </ul>

    <p>The finally clause, is used for the program cleanup</p>

    <p>Note fetch will return a promise </p>
    <p>if the value is above 400 then the server is not responding</p>
    <p> if it is 200 then it is running </p>
    <p> Let us use to fetch data from public api</p>
    <ul> Getting a response is a two stage process
        <li>The first response delivers the status of the server</li> 
        <li>Basically the first item is present to check whether connection is established</li>
        <li>ok, returns a boolean and therefore returns true if the HTTP status code is 200-299, we need to call the body in different formats</li>
    </ul>
</body>
<script src="21_FetchApi.js"></script>
</html>